# Site settings
title: Davis on Data - Machine learning trends, research, and evidence-based ramblings
email:
description: "Machine learning trends, research, and evidence-based ramblings"
baseurl: ""
url: "http://dblalock.github.io"
github_username:  dblalock

# Build settings
permalink: pretty
