# Site settings
title: Davis Talks Data - Machine learning research, trends, and evidence-based ramblings
email:
description: "Machine learning research, trends, and evidence-based ramblings"
baseurl: ""
url: "http://dblalock.github.io"
github_username:  dblalock

# Build settings
permalink: pretty
